### ISSUE TITLE
New version 1.28 won't compile

### ISSUE THREAD

**Issue by lesleyblankendal** [KKBOX/CompassApp#262]
When I watch a previous project that worked in the old version the clean and compile window will be blank. When I change a sass file, no CSS is compiled.

When trying to change the folders in 'change options' I get this message (on both local and network mapped drives):
![bug](https://cloud.githubusercontent.com/assets/4315309/4161942/e1a7cdbe-34d4-11e4-8fcb-fd407495d91a.png)

**Comment by lesleyblankendal** [comment]
Damn, I just now see the unread notification :(
I can still test if I'm not way way to late...

**Comment by hlb** [comment]
@lesleyblankendal sure! please mail to contact@kktix.com and get our latest beta :)
