### ISSUE TITLE
uninitialized constant Tray::SimpleLivereload

### ISSUE THREAD

**Issue by EricScottSembrat** [KKBOX/CompassApp#263]
I'm receiving an error upon usage of the new version of Compass.app.

Any time I pick a Sass project, I receive this error.
![screen shot 2014-09-05 at 11 01 13 am](https://cloud.githubusercontent.com/assets/2601827/4166707/7f0dddcc-350d-11e4-96bf-ad0583467aa8.png)

App: 1.28.1
OSX: 10.9.4
Java: 1.7.0_67_b01

The full error log:

uninitialized constant Tray::SimpleLivereload
org/jruby/RubyModule.java:2723:in `const_missing'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:532:in `stop_watch'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:425:in `watch'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app.rb:230:in `try'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:424:in `watch'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:167:in `compass_switch_handler'
anon_class1524866390_106797294.gen:13:in `handleEvent'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:70:in `run'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:129:in `run_tray'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:145:in `(root)'
org/jruby/RubyKernel.java:1065:in `require'
file:/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
file:/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by brunoatwork** [comment]
Any resolution on this issue? Having the same problem here.

**Comment by hlb** [comment]
v1.29 will release soon.
