### ISSUE TITLE
Problems with new version continue - Can I please have a link to downgrade ASAP

### ISSUE THREAD

**Issue by SirClickALot** [KKBOX/CompassApp#265]
Dear Authors,

After upgrading yesterday morning I could not compile anymore.

Today I received a further upgrade which, while different in its behaviour is still very problematic...

No such process - No message available
org/jruby/RubyFile.java:592:in `chmod'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/util.rb:1199:in `atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/util.rb:1197:in `atomic_create_and_write_file'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/cache_stores/filesystem.rb:39:in `_store'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/cache_stores/base.rb:51:in `store'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/cache_stores/chain.rb:19:in `store'
org/jruby/RubyArray.java:1613:in `each'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/cache_stores/chain.rb:19:in `store'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/engine.rb:404:in `_to_tree'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/engine.rb:299:in `to_tree'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:178:in `compute_dependencies'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/tree/node.rb:193:in `each'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/tree/node.rb:192:in `each'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyArray.java:1613:in `each'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyEnumerable.java:512:in `grep'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:164:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:164:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:164:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:164:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:164:in `dependency_updated?'
org/jruby/RubyProc.java:271:in `call'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:211:in `update_stylesheets'
org/jruby/RubyArray.java:1613:in `each'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
C:/local/compass.app/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:294:in `watch'
C:/local/compass.app/lib/ruby/compass_1.0/compass-1.0.0/lib/compass/sass_compiler.rb:46:in `watch!'
C:/local/compass.app/lib/ruby/compass_1.0/compass-1.0.0/lib/compass/commands/watch_project.rb:41:in `perform'
file:/C:/local/compass.app/compass-app.jar!/app_watcher.rb:12:in `watch!'
file:/C:/local/compass.app/compass-app.jar!/ui/tray.rb:447:in `watch'

I am using Windows 8.1, 8G, Java v8 update 11

Could I please have a link to the previous version as am not able to work anymore?

Thank you

Nick Abbott

**Comment by hlb** [comment]
v1.29 will release soon.
