### ISSUE TITLE
LiveReload no longer works

### ISSUE THREAD

**Issue by lumpysimon** [KKBOX/CompassApp#267]
Since upgrading to 1.28.1, LiveReload has stopped working. I'm not seeing any error messages, but when I save a .scss file Compass is compiling the new stylesheet, but it's somehow not getting passed to LiveReload.

I'm on Win7, the issue happens in both Firefox 32 and Chrome 37.

**Comment by hlb** [comment]
fixed in v1.29 and will release soon.

**Comment by lumpysimon** [comment]
Thank you for fixing this, it works perfectly in v1.29
