### ISSUE TITLE
Mac version crashing during watch

### ISSUE THREAD

**Issue by dvenckus** [KKBOX/CompassApp#271]
v1.28.1
No such file or directory - /Users/debra/.compass/extensions/activemodel-3.2.19/stylesheets
org/jruby/RubyFile.java:794:in `realpath'
/Applications/compass.app/Contents/Resources/lib/ruby/jruby/listen-1.1.6/lib/listen/listener.rb:247:in `initialize_directories_and_directories_records'
org/jruby/RubyArray.java:2412:in `map'
/Applications/compass.app/Contents/Resources/lib/ruby/jruby/listen-1.1.6/lib/listen/listener.rb:247:in `initialize_directories_and_directories_records'
/Applications/compass.app/Contents/Resources/lib/ruby/jruby/listen-1.1.6/lib/listen/listener.rb:33:in `initialize'
/Applications/compass.app/Contents/Resources/lib/ruby/jruby/listen-1.1.6/lib/listen.rb:51:in `_init_listener'
/Applications/compass.app/Contents/Resources/lib/ruby/jruby/listen-1.1.6/lib/listen.rb:27:in `to'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:394:in `create_listener'
org/jruby/RubyArray.java:2412:in `map'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:393:in `create_listener'
org/jruby/RubyMethod.java:140:in `call'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/hook/compass_patch.rb:12:in `create_listener'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/sass-3.4.1/lib/sass/plugin/compiler.rb:328:in `watch'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.0/lib/compass/sass_compiler.rb:46:in `watch!'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.0/lib/compass/commands/watch_project.rb:41:in `perform'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app_watcher.rb:12:in `watch!'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:447:in `watch'

**Comment by hlb** [comment]
v1.29 will release soon.
