### ISSUE TITLE
No Notifications or compass_app_log update

### ISSUE THREAD

**Issue by mikeleworthy** [KKBOX/CompassApp#281]
Hey,

I updated to compass 1.28.1. It is compiling, however I get no notifications and the compass_app_log file is not updated.

I have the latest version of Java and running windows 7. 
The Compass version is Default Sass 3.4.1 + Compass 1.0.0.

Hope that's enough info.
Mike.

**Comment by iget-esoares** [comment]
I also have the same problem! Compiles the project very slow, and dont show any update notification (it is enabled at Preference)

**Comment by hlb** [comment]
fixed in v1.29 and will release soon.
