### ISSUE TITLE
Mac version keeps crashing

### ISSUE THREAD

**Issue by juliancoates** [KKBOX/CompassApp#286]
happens increasingly frequently, since i got latest version of compassapp

every 20 minutes or so, but works fine in between crashes.

error message:

Cannot run program "/Applications/compass.app/Contents/Resources/lib/ruby/common/terminal-notifier/vendor/compassapp-notifier/compassapp-notifier.app/Contents/MacOS/compassapp" (in directory "/Applications/MAMP/htdocs/ACCESS/wordpress/wp-content/themes/wave_access"): error=2, No such file or directory
org/jruby/RubyIO.java:4344:in `popen'
/Applications/compass.app/Contents/Resources/lib/ruby/common/terminal-notifier/lib/terminal-notifier.rb:21:in `execute'
/Applications/compass.app/Contents/Resources/lib/ruby/common/terminal-notifier/lib/terminal-notifier.rb:50:in `notify'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/notifier.rb:10:in `notify'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app.rb:209:in `notify'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app.rb:41:in `show_and_clean_notifications'
org/jruby/RubyArray.java:1613:in `each'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app.rb:40:in `show_and_clean_notifications'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:71:in `run'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:129:in `run_tray'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:145:in `(root)'
org/jruby/RubyKernel.java:1065:in `require'
file:/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
file:/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'

**Comment by juliancoates** [comment]
12 days later, still crashing frequently :( 
what makes it worse is that the crash message is hidden behind other windows so I do not see it immediately and faff around wondering why my styles are not updating.

**Comment by juliancoates** [comment]
... and still it crashes. approximately once every hour at the moment.

**Comment by juliancoates** [comment]
still crashing just the same...

**Comment by hlb** [comment]
@juliancoates can you mail to contact@kktix.com, so we can provide you a beta version?

BTW, what is your OS and Jave version?

**Comment by juliancoates** [comment]
thanks,
Java 8 Update 31
OS X 10.9.5 (13F34)
i will email in a moment...

**Comment by juliancoates** [comment]
I've been using the beta version for 12 days now, much better thanks, no crashes. Only problem now is ccasionally it fails to update the css file after I make a change in a partial, but that is pretty rare.

**Comment by hlb** [comment]
@juliancoates can you mail the project zip to us, so we can test what happens?

**Comment by juliancoates** [comment]
sorry i cant send the whole project because it is client work. I could send you just the scss, I will try and do that in the next few hours, if that is useful to you.

**Comment by hlb** [comment]
@juliancoates thank you very much!

**Comment by juliancoates** [comment]
here are my scss files as requested, I hope you find them useful.

**Comment by hlb** [comment]
@juliancoates hmm, didn't get it. Can you send to contact@kktix.com instead?
