### ISSUE TITLE
Paid for Compass.app - no download

### ISSUE THREAD

**Issue by brookswilson** [KKBOX/CompassApp#289]
I paid $10 for your product and did not get a download link? Is this a rip-off? Should I contact PayPal?

**Comment by brookswilson** [comment]
You sent a payment of $10.00 USD to 願境網訊股份有限公司.
Feb 25, 2015 07:25:30 PST
Receipt No:4532-6460-6176-3016
Hello Thomas Wilson,

This charge will appear on your credit card statement as payment to PAYPAL *YUANJINGWAN.

Merchant information:
願境網訊股份有限公司
payment_paypal@kktix.com
26557557	Instructions to merchant:
None provided
Shipping information
Shipping method
Not specified
Description	Unit price	Qty	Amount
Compass.app
$10.00 USD	1	$10.00 USD

Discount:	-$0.00 USD
Total:	$10.00 USD
Receipt No: 4532-6460-6176-3016

**Comment by hlb** [comment]
@brookswilson hello, the download link has already sent to your PayPal email address on 2015/02/25 23:23:09 +0800. We have resent it again. You can also mail to contact@kktix.com to get your link :)
