### ISSUE TITLE
Question Regarding Adding Other Gem Files into Compass.app

### ISSUE THREAD

**Issue by andrewnprice** [KKBOX/CompassApp#291]
Hi, this may be a stupid question, but I am new to SASS/SCSS and I am trying to work on a Drupal page that uses Radix, and so I purchases compass.app to help me with that.  (I have tried using normal ruby to do this, and don't quite get it to be honest.)  Well long story short... I need access to some specific gem files to be able to do compile the Sass files included in with the theme that I am using... and I don't know how to do that.  More specifically compass_radix and a few others.  How do I get compass.app to include those?  I hate asking for help on this, but I feel like I have no idea what I am doing with compass, and I just want to be able to mess with this theme and figure it out, but I can't do that until I can get something to compile properly.  Thanks in advance for any help that you might be able to offer.

**Comment by hlb** [comment]
@andrewnprice please check https://github.com/KKBOX/CompassApp/wiki/Using-Compass-Extensions#example-install-fancy-buttons to install compass gems/extensions into Compass.app
