### ISSUE TITLE
CompassApp for Mac OS

### ISSUE THREAD

**Issue by alex-git** [KKBOX/CompassApp#293]
Just downloaded CompassApp for Mac OS, and when I click to open it, I get an alert that says I need to update to Java 1.7. When I click on this alert it brings me to Oracle's Install Java page, but only shows installs of version 7.0 and 8.0. How can I get my CompassApp up and running?

**Comment by hlb** [comment]
You can either download 8.0 (recommended) or 7.0. Both work. Java uses 1.7 as version name but 7.0 as... um... commercial name.

**Comment by alex-git** [comment]
Thanks Hib!
