### ISSUE TITLE
Compiling 1 of 3 scss files

### ISSUE THREAD

**Issue by csbrou** [KKBOX/CompassApp#296]
I have three .scss files that I need compiled but only one of them compiles on save. They are all in the same folder and I can get all of them to compile if I click 'Clean & Compile'. What am I doing wrong? I'm on Windows 7 x64. I am using Dreamweaver and version 1.29 of the CompassApp. Thanks for any suggestions you might have.

**Comment by hlb** [comment]
@csbrou can you zip the project and send to contact@kktix.com, so we can figure it out for you? :)

**Comment by csbrou** [comment]
Files are on their way. Thank you!

**Comment by hlb** [comment]
@csbrou we have tested your project in OSX 10.10 and Windows 7. Both work. But it is really slow and require 10s+ to update the changes

**Comment by csbrou** [comment]
Thanks for looking into this. It's still only compiling 1 of my 3 files. I've let it sit for a minute or so after a save with no result. I've tried it with and without Dreamweaver. I suppose there is something wonky in my environment.

**Comment by hlb** [comment]
@csbrou can you try http://www.sublimetext.com/ instead of Dreamweaver?

**Comment by csbrou** [comment]
Thanks for the tip. I downloaded it and tried it out. I do like some of the features. Honestly, the main reason I use Dreamweaver is for file management and synchronization. We don’t use versioning (git/svn) on all of our projects and I find that on large ecommerce packages like Magento, I need help remembering what files I edited.

Do you think Dreamweaver is interfering with your app and that’s why not all of my files are compiling on save? Any thoughts on a good file sync tool?



Carol Brouwer
Tempora Resources, Ltd.
o: 832.912.7959  • c: 713.408.6970
www.tempora.com<http://www.tempora.com/> • carol.brouwer@tempora.com<mailto:carol.brouwer@tempora.com>

**Comment by hlb** [comment]
@csbrou we use git and command line sync tool... sorry ^_^;

**Comment by csbrou** [comment]
@hlb - Just a quick update to let you know we moved the project into SVN and I abandoned DreamWeaver. CompassApp is working perfectly now. Thanks again for your help.

**Comment by hlb** [comment]
@csbrou :+1:
